# vim:set noet sts=0 sw=8 ts=8 ft=dockerfile:
# test building
FROM golang:1.23-bookworm
RUN apt-get update -y
RUN apt-get install -y clang
RUN curl -LO https://musl.cc/aarch64-linux-musl-cross.tgz && \
    tar -xzf aarch64-linux-musl-cross.tgz && \
    mv aarch64-linux-musl-cross /usr/local/musl-cross-aarch64

RUN apt-get install -y \
	gcc-mingw-w64-x86-64 \
	gcc-multilib \
	musl-dev \
	musl-tools \
	bash \
	upx

ENV PATH="/usr/local/musl-cross-aarch64/bin:${PATH}"
COPY . /app
WORKDIR /app
# RUN go mod tidy
CMD bash scripts/build.sh -a
